if (self.CavalryLogger) { CavalryLogger.start_js(["D139d"]); }

__d("CometIXTContentTriggerRootQuery$Parameters",[],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:"3736240879837617",metadata:{},name:"CometIXTContentTriggerRootQuery",operationKind:"query",text:null}};e.exports=a}),null);
__d("CometIXTContentTriggerEntryPoint.entrypoint",["CometIXTContentTriggerRootQuery$Parameters","JSResourceForInteraction","React","WebPixelRatio","uuid"],(function(a,b,c,d,e,f){"use strict";b("React");a={getPreloadProps:function(a){return{queries:{reference:{parameters:b("CometIXTContentTriggerRootQuery$Parameters"),variables:{input:babelHelpers["extends"]({},a,{nt_context:null,trigger_session_id:b("uuid")()}),scale:b("WebPixelRatio").get()}}}}},root:b("JSResourceForInteraction")("CometIXTContentTriggerRoot.react").__setRef("CometIXTContentTriggerEntryPoint.entrypoint")};e.exports=a}),null);
__d("useIXTContentTriggerDialog",["CometIXTContentTriggerEntryPoint.entrypoint","useCometEntryPointDialog"],(function(a,b,c,d,e,f){"use strict";function a(a){return b("useCometEntryPointDialog")(b("CometIXTContentTriggerEntryPoint.entrypoint"),a)}e.exports=a}),null);
__d("CometMisinfoSeeWhyDialogQuery$Parameters",[],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:"5479850135374552",metadata:{},name:"CometMisinfoSeeWhyDialogQuery",operationKind:"query",text:null}};e.exports=a}),null);
__d("CometMisinfoSeeWhyDialogEntryPoint.entrypoint",["CometMisinfoSeeWhyDialogQuery$Parameters","JSResourceForInteraction","WebPixelRatio"],(function(a,b,c,d,e,f){"use strict";a={getPreloadProps:function(a){var c;a=a.entID;a=(c=a)==null?void 0:c.split(":").filter(function(a){return a!==""}).pop();return{extraProps:{entID:a},queries:{cometMisinfoSeeWhyDialogQueryReference:{parameters:b("CometMisinfoSeeWhyDialogQuery$Parameters"),variables:{entID:a,scale:b("WebPixelRatio").get()}}}}},root:b("JSResourceForInteraction")("CometMisinfoSeeWhyDialog.react").__setRef("CometMisinfoSeeWhyDialogEntryPoint.entrypoint")};e.exports=a}),null);
__d("useInformTreatmentFollowupExperience",["CometMisinfoSeeWhyDialogEntryPoint.entrypoint","gkx","useCometEntryPointDialog","useIXTContentTriggerDialog"],(function(a,b,c,d,e,f){"use strict";e.exports=a;var g=b("gkx")("1770065");function a(a){var c=a.contentID,d=a.entryPoint,e=a.ixtTriggerEvent;a=a.location;c=c.split(":").filter(function(a){return a!==""}).pop();var f=b("useCometEntryPointDialog")(b("CometMisinfoSeeWhyDialogEntryPoint.entrypoint"),{entID:c}),h=f[0];f=f[1];a=b("useIXTContentTriggerDialog")({content_id:c,entry_point:(c=d)!=null?c:"UNKNOWN",location:(d=a)!=null?d:"UNKNOWN",trigger_event_type:(c=e)!=null?c:"INFORM_TREATMENT_SEE_WHY"});var i=a[0];d=a[1];if(e!=null&&g)return[function(){return i({})},d];else return[h,f]}}),null);
__d("CixWarningScreensFalcoEvent",["FalcoLoggerInternal","getFalcoLogPolicy_DO_NOT_USE"],(function(a,b,c,d,e,f){"use strict";a=b("getFalcoLogPolicy_DO_NOT_USE")("1743358");c=b("FalcoLoggerInternal").create("cix_warning_screens",a);e.exports=c}),null);
__d("WarningScreenType",[],(function(a,b,c,d,e,f){a=Object.freeze({GRAPHIC:"Violence and Gore",OBJECTIONABLE:"Sexual",HATE:"Hate",PROFANITY:"Profanity",POLITICAL:"Politically Charged",CHILD_ABUSE_NON_SEXUAL:"Child Abuse (non-sexual)",SENSITIVE:"Sensitive",CRUEL:"Cruel",MATURE_ONLY_14_AND_OVER:"Mature Only 14 And Over",ANIMAL_VIOLENCE:"Animal Violence",SENSITIVE_TEXT:"Sensitive Text",FALSE_NEWS:"False News",FALSE_HEADLINE_NEWS:"False Headline News",MISLEADING_NEWS:"Misleading News",ALTERED_MEDIA:"Altered Media",MISSING_CONTEXT:"Missing Context",GOVERNMENT_CORRECTION:"Government Correction",CENSUS_MISINFO:"Census Misinfo",CENSUS_BORDERLINE:"Census Borderline",COVID_ELECTION_BORDERLINE:"Covd Election Borderline",WIDELY_DEBUNKED_HOAX_COVID:"Widely Debunked Hoax Covid",HEALTH_GENERIC:"Health Generic",GENERIC_INFORM_TREATMENT:"Generic Inform Treatment",CLIMATE_GENERIC_INFORM_TREATMENT:"Climate Science Generic Inform Treatment",NEWSWORTHY:"Newsworthy",SELF_APPLIED_GRAPHIC_VIOLENCE:"Self Applied Graphic Violence",CIVIC_VOTER_INFORM_TREATMENT:"Civic Voter Inform Treatment",CIVIC_VOTER_INFORM_TREATMENT_FOR_MM:"Civic Voter Inform Treatment For Myanmar",CIVIC_VOTER_INFORM_TREATMENT_FOR_BR:"Civic Voter Inform Treatment For Brazil",CIVIC_VOTER_INFORM_TREATMENT_FOR_ID:"Civic Voter Inform Treatment For Indonesia",CIVIC_FACTS_ABOUT_VOTING_INFORM_TREATMENT:"Civic Facts About Voting Inform Treatment",HACK_AND_LEAK:"Hack And Leak",GRAPHIC_MISINFO:"Graphic Misinfo",WIDELY_DEBUNKED_HOAX_VACCINE:"Widely Debunked Hoax Vaccine",WORK_RECRUITING_GROUP_POST:"Recruiting Group Post"});e.exports=a}),null);
__d("CometWarningScreenClientLogger",["CixWarningScreensFalcoEvent","WarningScreenType"],(function(a,b,c,d,e,f){"use strict";f.logWarningScreenEvent=a;function a(a,c,d,e,f,h,i,j,k,l,m,n){var o=c==null?void 0:c.split(":").filter(function(a){return a!==""}).pop();b("CixWarningScreensFalcoEvent").log(function(){return{action:a,content_id_raw:o,endpoint:d,event:e,generic_inform_treatment_case:l,integrity_ui_element:f,product:m,render_type:n,story_ent_identifier_graphql_id:h,story_render_location:i,surface:j,top_warning_screen_category:g(k)}})}function g(a){if(a==null)return null;a=a;return b("WarningScreenType")[a]}}),null);
__d("WarningScreenRenderType",[],(function(a,b,c,d,e,f){a=Object.freeze({FULL_COVER:"FULL_COVER",LIGHTWEIGHT:"LIGHTWEIGHT"});e.exports=a}),null);